# Generated by Django 2.2.10 on 2020-02-09 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignments',
            old_name='assignment_name',
            new_name='name',
        ),
    ]
