# Generated by Django 2.2.10 on 2020-02-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradeWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight1', models.IntegerField()),
                ('weight2', models.IntegerField()),
                ('weight3', models.IntegerField()),
                ('weight4', models.IntegerField()),
                ('weight5', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NewGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(max_length=30)),
                ('assignment_category', models.CharField(max_length=30)),
                ('recieved_grade', models.IntegerField()),
                ('total_points', models.IntegerField()),
            ],
        ),
    ]
