# Generated by Django 2.2.10 on 2020-02-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='newgrade',
            name='percentage',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
