# Generated by Django 2.2.10 on 2020-02-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_name', models.CharField(max_length=50)),
                ('instructor_office_hrs', models.CharField(max_length=20)),
                ('instructor_email', models.CharField(max_length=40)),
                ('course_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GradeWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight1', models.IntegerField()),
                ('weight2', models.IntegerField()),
                ('weight3', models.IntegerField()),
                ('weight4', models.IntegerField()),
                ('weight5', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('user_id', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
