# Generated by Django 2.2.10 on 2020-02-09 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GradeWeight',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
